// Which model types may render from a pre-made GLB (public/assets/models/<slug>.glb) instead of the
// procedural figure. Key = `<datasheet id>/<datasheet modelId>` (Model.datasheetModelId in the engine
// state, composition[].modelId in the datasheet JSON). Value = slug = GLB file name without ".glb".
//
// TO ENABLE A MODEL: drop <slug>.glb into public/assets/models/ and add the slug to ENABLED_GLB_SLUGS.
// Nothing else changes. Slugs not listed there are never requested and keep the procedural figure.
export const ENABLED_GLB_SLUGS: readonly string[] = [
  'captain-octavius',
  'librarian-tantus',
  'infernus-sergeant',
  'infernus-marine',
  'terminator-sergeant',
  'terminator',
  'warboss-gordrang',
  'boss-nob',
  'boy',
  'deff-dread',
  'deffkopta',
  'necron-warrior',
  'necron-overlord',
  'skorpekh-destroyer',
  'canoptek-doomstalker',
  'canoptek-scarab',
  'aranis-zarkan',
  'possessed',
  'legionary-champion',
  'legionary',
  'cultist-champion',
  'cultist',
  'terror-of-vardenghast',
  'psychophage',
  'termagant',
  'barbgaunt',
  'von-ryan-leaper',
  'canoness-adalya',
  'sister-superior',
  'battle-sister',
  'celestian-sacresant',
  'arco-flagellant',
  'cadian-sergeant',
  'cadian-trooper',
  'lord-marshal-karsk',
  'cadian-veteran',
  'cadian-medic',
  'cadian-standard-bearer',
  'bombast-field-gun',
  'malleus-rocket-battery',
  'armoured-sentinel',
  'librarian-aurellios',
  'gk-terminator-justicar',
  'gk-terminator',
  'gk-terminator-psycannon',
  'strike-justicar',
  'strike-knight',
  'strike-psilencer',
  'nemesis-dreadknight',
  'aun-shar',
  'shasnel-dtano',
  'fire-warrior-rifle',
  'fire-warrior-carbine',
  'fire-warrior-shasui',
  'stealth-shasvre',
  'stealth-shasui',
  'ghostkeel',
]

export const GLB_SLUG_BY_MODEL: Readonly<Record<string, string>> = {
  'sm.captain-octavius/captain': 'captain-octavius',
  'sm.librarian-tantus/librarian': 'librarian-tantus',
  'sm.infernus-squad/sergeant': 'infernus-sergeant',
  'sm.infernus-squad/marine': 'infernus-marine',
  'sm.terminator-squad/sergeant': 'terminator-sergeant',
  'sm.terminator-squad/gunner': 'terminator',
  'sm.terminator-squad/terminator': 'terminator',
  'ork.warboss-gordrang/gordrang': 'warboss-gordrang',
  'ork.boyz/boss-nob': 'boss-nob',
  'ork.boyz/boy-choppa': 'boy',
  'ork.boyz/boy-shoota': 'boy',
  'ork.boyz/boy-heavy': 'boy',
  'ork.deff-dread/deff-dread': 'deff-dread',
  'ork.deffkoptas/kopta-blasta': 'deffkopta',
  'ork.deffkoptas/kopta-rokkits': 'deffkopta',
  // Necrons: no GLBs yet. Listed so enabling one is just dropping the file in and adding its slug above;
  // until then glbSlugFor() returns undefined and the procedural kit (kitConfigs.ts) draws the model.
  'nec.necron-warriors/warrior-flayer': 'necron-warrior',
  'nec.necron-warriors/warrior-reaper': 'necron-warrior',
  'nec.overlord-amonhotekh/overlord': 'necron-overlord',
  'nec.skorpekh-destroyers/destroyer': 'skorpekh-destroyer',
  'nec.canoptek-doomstalker/doomstalker': 'canoptek-doomstalker',
  'nec.canoptek-scarab-swarms/swarm': 'canoptek-scarab',
  // Chaos Space Marines: no GLBs yet, same arrangement as the Necrons above.
  'csm.aranis-zarkan/zarkan': 'aranis-zarkan',
  'csm.possessed/possessed': 'possessed',
  'csm.legionaries/champion': 'legionary-champion',
  'csm.legionaries/meltagun': 'legionary',
  'csm.legionaries/heavy-bolter': 'legionary',
  'csm.legionaries/boltgun': 'legionary',
  'csm.cultist-mob/champion': 'cultist-champion',
  'csm.cultist-mob/cultist': 'cultist',
  // Tyranids: no GLBs yet; same deal as the Necrons above (procedural kits in kitConfigs.ts draw them).
  'tyr.terror-of-vardenghast/prime': 'terror-of-vardenghast',
  'tyr.psychophage/psychophage': 'psychophage',
  'tyr.termagants/termagant': 'termagant',
  'tyr.barbgaunts/barbgaunt': 'barbgaunt',
  'tyr.von-ryans-leapers/leaper': 'von-ryan-leaper',
  // Adepta Sororitas: no GLBs yet — same story as the Necrons above; the procedural kits draw them until a file lands.
  'ade.canoness-adalya/canoness': 'canoness-adalya',
  'ade.battle-sisters-squad/superior': 'sister-superior',
  'ade.battle-sisters-squad/sister-flamer': 'battle-sister',
  'ade.battle-sisters-squad/sister-heavy-flamer': 'battle-sister',
  'ade.battle-sisters-squad/sister-simulacrum': 'battle-sister',
  'ade.battle-sisters-squad/sister': 'battle-sister',
  'ade.celestian-sacresants/sacresant': 'celestian-sacresant',
  'ade.arco-flagellants/arco': 'arco-flagellant',
  // Astra Militarum: no GLBs yet, same arrangement as the Necrons above (slug unlisted in ENABLED_GLB_SLUGS = procedural).
  'am.cadian-shock-troops/sergeant': 'cadian-sergeant',
  'am.cadian-shock-troops/trooper': 'cadian-trooper',
  'am.command-squad-karsk/karsk': 'lord-marshal-karsk',
  'am.command-squad-karsk/veteran': 'cadian-veteran',
  'am.command-squad-karsk/veteran-medic': 'cadian-medic',
  'am.command-squad-karsk/veteran-standard': 'cadian-standard-bearer',
  'am.field-ordnance-battery/gun-bombast': 'bombast-field-gun',
  'am.field-ordnance-battery/gun-malleus': 'malleus-rocket-battery',
  'am.armoured-sentinels/sentinel': 'armoured-sentinel',

  // Grey Knights (MGSD GLBs).
  'gk.librarian-aurellios/librarian': 'librarian-aurellios',
  'gk.brotherhood-terminator-squad/justicar': 'gk-terminator-justicar',
  'gk.brotherhood-terminator-squad/terminator': 'gk-terminator',
  'gk.brotherhood-terminator-squad/psycannon': 'gk-terminator-psycannon',
  'gk.strike-squad/justicar': 'strike-justicar',
  'gk.strike-squad/knight': 'strike-knight',
  'gk.strike-squad/psilencer': 'strike-psilencer',
  'gk.nemesis-dreadknight/dreadknight': 'nemesis-dreadknight',

  // T'au Empire (MGSD GLBs).
  'tau.aun-shar/aun-shar': 'aun-shar',
  'tau.shasnel-dtano/fireblade': 'shasnel-dtano',
  'tau.strike-team/fire-warrior-rifle': 'fire-warrior-rifle',
  'tau.strike-team/fire-warrior-carbine': 'fire-warrior-carbine',
  'tau.strike-team/shasui': 'fire-warrior-shasui',
  'tau.stealth-battlesuits/shasvre': 'stealth-shasvre',
  'tau.stealth-battlesuits/shasui': 'stealth-shasui',
  'tau.ghostkeel/ghostkeel': 'ghostkeel',
}

/** The enabled GLB slug for a model type, or undefined (use the procedural figure). */
export function glbSlugFor(datasheetId: string, modelId: string | undefined): string | undefined {
  if (!modelId) return undefined
  const slug = GLB_SLUG_BY_MODEL[`${datasheetId}/${modelId}`]
  return slug && ENABLED_GLB_SLUGS.includes(slug) ? slug : undefined
}
