// Per-kit visual dressing (30-figures.md §2/§4 flavour, not rules data). Keyed by KitId so
// Figure.tsx can go straight from resolveFigureKit() to "what does this look like".
import type { BipedConfig, KitId, VehicleConfig } from './types'

export const BODY_KIND: Record<KitId, 'biped' | 'vehicle' | 'swarm'> = {
  'sm-tacticus': 'biped',
  'sm-terminator': 'biped',
  'ork-boy': 'biped',
  'ork-warboss': 'biped',
  'ork-deff-dread': 'biped',
  'ork-deffkopta': 'vehicle',
  'nec-warrior': 'biped',
  'nec-overlord': 'biped',
  'nec-skorpekh': 'biped',
  'nec-doomstalker': 'biped',
  'nec-scarab': 'swarm',
  'csm-legionary': 'biped',
  'csm-zarkan': 'biped',
  'csm-possessed': 'biped',
  'csm-cultist': 'biped',
  'tyr-prime': 'biped',
  'tyr-psychophage': 'biped',
  'tyr-termagant': 'biped',
  'tyr-barbgaunt': 'biped',
  'tyr-leaper': 'biped',
  'generic-infantry': 'biped',
  'generic-heavy': 'biped',
  'generic-monster': 'biped',
  'generic-vehicle': 'vehicle',
}

export const BIPED_CONFIG: Partial<Record<KitId, BipedConfig>> = {
  'sm-tacticus': {
    headShape: 'marine-helmet',
    rightWeapon: 'bolt-rifle',
    leftWeapon: 'none',
    bulk: 1,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'none',
  },
  'sm-terminator': {
    headShape: 'terminator-helmet',
    rightWeapon: 'storm-bolter',
    leftWeapon: 'power-fist',
    bulk: 1.5,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
  },
  'ork-boy': {
    headShape: 'ork-head',
    rightWeapon: 'choppa',
    leftWeapon: 'slugga',
    bulk: 1.15,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'ork',
  },
  'ork-warboss': {
    headShape: 'ork-boss-head',
    rightWeapon: 'power-klaw',
    leftWeapon: 'boss-choppa',
    bulk: 1.7,
    hasBackpack: false,
    shoulderPads: 'large',
    hasCape: true,
    skin: 'ork',
  },
  'ork-deff-dread': {
    headShape: 'ork-head',
    rightWeapon: 'twin-claw',
    leftWeapon: 'twin-claw',
    bulk: 2.3,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
  },
  // Necrons: dark metal frames (primary), arms in bare metal, green kept as the glow (eyes, chest core, weapon
  // emitters) and gold as trim — the faction paintScheme read as a skeleton soldier, not a green marine.
  'nec-warrior': {
    headShape: 'necron-skull',
    rightWeapon: 'gauss-flayer',
    leftWeapon: 'none',
    bulk: 1,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
    limbColor: 'metal',
    chestCore: true,
  },
  'nec-overlord': {
    headShape: 'necron-lord',
    rightWeapon: 'warscythe',
    leftWeapon: 'none',
    bulk: 1.45,
    hasBackpack: false,
    shoulderPads: 'small',
    hasCape: true,
    skin: 'none',
    limbColor: 'metal',
    chestCore: true,
  },
  'nec-skorpekh': {
    headShape: 'necron-skull',
    rightWeapon: 'hyperphase-blade',
    leftWeapon: 'hyperphase-blade',
    bulk: 1.5,
    hasBackpack: true,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
    limbColor: 'metal',
    chestCore: true,
  },
  'nec-doomstalker': {
    headShape: 'necron-skull',
    rightWeapon: 'doomsday-blaster',
    leftWeapon: 'twin-claw',
    bulk: 2.2,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
    limbColor: 'metal',
    chestCore: true,
  },
  // Chaos Space Marines: blue-black plate with crimson limbs, brass horns/trim and violet-glow eyes (the decal slot).
  'csm-legionary': {
    headShape: 'chaos-helmet',
    rightWeapon: 'chaos-bolter',
    leftWeapon: 'none',
    bulk: 1.1,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'none',
    chestPlate: true,
  },
  'csm-zarkan': {
    headShape: 'chaos-sorcerer',
    rightWeapon: 'ritual-staff',
    leftWeapon: 'slugga',
    bulk: 1.4,
    hasBackpack: false,
    shoulderPads: 'large',
    hasCape: true,
    skin: 'none',
    chestPlate: true,
  },
  'csm-possessed': {
    headShape: 'possessed-head',
    rightWeapon: 'mutant-claw',
    leftWeapon: 'mutant-claw',
    bulk: 1.75,
    hasBackpack: false,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'daemon',
    limbColor: 'skin',
  },
  'csm-cultist': {
    headShape: 'cultist-hood',
    rightWeapon: 'rusty-blade',
    leftWeapon: 'slugga',
    bulk: 0.95,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
    torsoColor: 'secondary',
  },
  // Tyranids: bone-white carapace and legs (primary), purple limbs (secondary), red trim, dark chitin (metal) for
  // claws/spines, green decal as the glow (eyes, spine tips, spore sacs). Each unit has its own head shape and
  // silhouette extra: wings (Prime), hulking bulk (Psychophage), launcher + backpack (Barbgaunt), low tail (Leaper).
  'tyr-termagant': {
    headShape: 'tyranid-head',
    rightWeapon: 'fleshborer',
    leftWeapon: 'rending-claws',
    bulk: 0.9,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
    tail: true,
    hunch: 0.18,
  },
  'tyr-barbgaunt': {
    headShape: 'tyranid-head',
    rightWeapon: 'barblauncher',
    leftWeapon: 'rending-claws',
    bulk: 1.25,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'none',
    tail: true,
    dorsalSpines: true,
    hunch: 0.1,
  },
  'tyr-leaper': {
    headShape: 'tyranid-head',
    rightWeapon: 'scything-talons',
    leftWeapon: 'scything-talons',
    bulk: 1,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
    tail: true,
    dorsalSpines: true,
    hunch: 0.3,
  },
  'tyr-prime': {
    headShape: 'tyranid-prime-head',
    rightWeapon: 'scything-talons',
    leftWeapon: 'scything-talons',
    bulk: 1.45,
    hasBackpack: false,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
    tail: true,
    wings: true,
    dorsalSpines: true,
    extraArms: true,
    hunch: 0.12,
  },
  'tyr-psychophage': {
    headShape: 'tyranid-brute-head',
    rightWeapon: 'torrent-maw',
    leftWeapon: 'scything-talons',
    bulk: 2.3,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
    tail: true,
    dorsalSpines: true,
    hunch: 0.25,
  },
  'generic-infantry': {
    headShape: 'generic-head',
    rightWeapon: 'bolt-rifle',
    leftWeapon: 'none',
    bulk: 1,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
  },
  'generic-heavy': {
    headShape: 'generic-head',
    rightWeapon: 'storm-bolter',
    leftWeapon: 'none',
    bulk: 1.5,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'none',
  },
  'generic-monster': {
    headShape: 'generic-head',
    rightWeapon: 'twin-claw',
    leftWeapon: 'twin-claw',
    bulk: 2.2,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
  },
}

export const VEHICLE_CONFIG: Partial<Record<KitId, VehicleConfig>> = {
  'ork-deffkopta': { weapon: 'kustom-mega-blasta', hasRotor: true },
  'generic-vehicle': { weapon: 'none', hasRotor: false },
}
