// Per-kit visual dressing (30-figures.md §2/§4 flavour, not rules data). Keyed by KitId so
// Figure.tsx can go straight from resolveFigureKit() to "what does this look like".
import type { ArtilleryConfig, BipedConfig, KitId, VehicleConfig } from './types'

export const BODY_KIND: Record<KitId, 'biped' | 'vehicle' | 'swarm' | 'artillery'> = {
  'sm-tacticus': 'biped',
  'sm-terminator': 'biped',
  'ork-boy': 'biped',
  'ork-warboss': 'biped',
  'ork-deff-dread': 'biped',
  'ork-deffkopta': 'vehicle',
  'nec-warrior': 'biped',
  'nec-overlord': 'biped',
  'nec-skorpekh': 'biped',
  'nec-doomstalker': 'biped',
  'nec-scarab': 'swarm',
  'csm-legionary': 'biped',
  'csm-zarkan': 'biped',
  'csm-possessed': 'biped',
  'csm-cultist': 'biped',
  'tyr-prime': 'biped',
  'tyr-psychophage': 'biped',
  'tyr-termagant': 'biped',
  'tyr-barbgaunt': 'biped',
  'tyr-leaper': 'biped',
  'am-guardsman': 'biped',
  'am-sergeant': 'biped',
  'am-officer': 'biped',
  'am-veteran': 'biped',
  'am-medic': 'biped',
  'am-standard': 'biped',
  'am-sentinel': 'biped',
  'am-field-gun': 'artillery',
  'am-rocket-battery': 'artillery',
  'gk-knight': 'biped',
  'gk-terminator': 'biped',
  'gk-librarian': 'biped',
  'gk-dreadknight': 'biped',
  'tau-fire-warrior': 'biped',
  'tau-shasui': 'biped',
  'tau-fireblade': 'biped',
  'tau-ethereal': 'biped',
  'tau-stealth': 'biped',
  'tau-ghostkeel': 'biped',
  'generic-infantry': 'biped',
  'generic-heavy': 'biped',
  'generic-monster': 'biped',
  'generic-vehicle': 'vehicle',
  'ade-canoness': 'biped',
  'ade-sister': 'biped',
  'ade-sister-superior': 'biped',
  'ade-sister-flamer': 'biped',
  'ade-sister-heavy-flamer': 'biped',
  'ade-sister-simulacrum': 'biped',
  'ade-sacresant': 'biped',
  'ade-arco': 'biped',
}

export const BIPED_CONFIG: Partial<Record<KitId, BipedConfig>> = {
  'sm-tacticus': {
    headShape: 'marine-helmet',
    rightWeapon: 'bolt-rifle',
    leftWeapon: 'none',
    bulk: 1,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'none',
  },
  'sm-terminator': {
    headShape: 'terminator-helmet',
    rightWeapon: 'storm-bolter',
    leftWeapon: 'power-fist',
    bulk: 1.5,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
  },
  'ork-boy': {
    headShape: 'ork-head',
    rightWeapon: 'choppa',
    leftWeapon: 'slugga',
    bulk: 1.15,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'ork',
  },
  'ork-warboss': {
    headShape: 'ork-boss-head',
    rightWeapon: 'power-klaw',
    leftWeapon: 'boss-choppa',
    bulk: 1.7,
    hasBackpack: false,
    shoulderPads: 'large',
    hasCape: true,
    skin: 'ork',
  },
  'ork-deff-dread': {
    headShape: 'ork-head',
    rightWeapon: 'twin-claw',
    leftWeapon: 'twin-claw',
    bulk: 2.3,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
  },
  // Necrons: dark metal frames (primary), arms in bare metal, green kept as the glow (eyes, chest core, weapon
  // emitters) and gold as trim — the faction paintScheme read as a skeleton soldier, not a green marine.
  'nec-warrior': {
    headShape: 'necron-skull',
    rightWeapon: 'gauss-flayer',
    leftWeapon: 'none',
    bulk: 1,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
    limbColor: 'metal',
    chestCore: true,
  },
  'nec-overlord': {
    headShape: 'necron-lord',
    rightWeapon: 'warscythe',
    leftWeapon: 'none',
    bulk: 1.45,
    hasBackpack: false,
    shoulderPads: 'small',
    hasCape: true,
    skin: 'none',
    limbColor: 'metal',
    chestCore: true,
  },
  'nec-skorpekh': {
    headShape: 'necron-skull',
    rightWeapon: 'hyperphase-blade',
    leftWeapon: 'hyperphase-blade',
    bulk: 1.5,
    hasBackpack: true,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
    limbColor: 'metal',
    chestCore: true,
  },
  'nec-doomstalker': {
    headShape: 'necron-skull',
    rightWeapon: 'doomsday-blaster',
    leftWeapon: 'twin-claw',
    bulk: 2.2,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
    limbColor: 'metal',
    chestCore: true,
  },
  // Chaos Space Marines: blue-black plate with crimson limbs, brass horns/trim and violet-glow eyes (the decal slot).
  'csm-legionary': {
    headShape: 'chaos-helmet',
    rightWeapon: 'chaos-bolter',
    leftWeapon: 'none',
    bulk: 1.1,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'none',
    chestPlate: true,
  },
  'csm-zarkan': {
    headShape: 'chaos-sorcerer',
    rightWeapon: 'ritual-staff',
    leftWeapon: 'slugga',
    bulk: 1.4,
    hasBackpack: false,
    shoulderPads: 'large',
    hasCape: true,
    skin: 'none',
    chestPlate: true,
  },
  'csm-possessed': {
    headShape: 'possessed-head',
    rightWeapon: 'mutant-claw',
    leftWeapon: 'mutant-claw',
    bulk: 1.75,
    hasBackpack: false,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'daemon',
    limbColor: 'skin',
  },
  'csm-cultist': {
    headShape: 'cultist-hood',
    rightWeapon: 'rusty-blade',
    leftWeapon: 'slugga',
    bulk: 0.95,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
    torsoColor: 'secondary',
  },
  // Tyranids: bone-white carapace and legs (primary), purple limbs (secondary), red trim, dark chitin (metal) for
  // claws/spines, green decal as the glow (eyes, spine tips, spore sacs). Each unit has its own head shape and
  // silhouette extra: wings (Prime), hulking bulk (Psychophage), launcher + backpack (Barbgaunt), low tail (Leaper).
  'tyr-termagant': {
    headShape: 'tyranid-head',
    rightWeapon: 'fleshborer',
    leftWeapon: 'rending-claws',
    bulk: 0.9,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
    tail: true,
    hunch: 0.18,
  },
  'tyr-barbgaunt': {
    headShape: 'tyranid-head',
    rightWeapon: 'barblauncher',
    leftWeapon: 'rending-claws',
    bulk: 1.25,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'none',
    tail: true,
    dorsalSpines: true,
    hunch: 0.1,
  },
  'tyr-leaper': {
    headShape: 'tyranid-head',
    rightWeapon: 'scything-talons',
    leftWeapon: 'scything-talons',
    bulk: 1,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
    tail: true,
    dorsalSpines: true,
    hunch: 0.3,
  },
  'tyr-prime': {
    headShape: 'tyranid-prime-head',
    rightWeapon: 'scything-talons',
    leftWeapon: 'scything-talons',
    bulk: 1.45,
    hasBackpack: false,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
    tail: true,
    wings: true,
    dorsalSpines: true,
    extraArms: true,
    hunch: 0.12,
  },
  'tyr-psychophage': {
    headShape: 'tyranid-brute-head',
    rightWeapon: 'torrent-maw',
    leftWeapon: 'scything-talons',
    bulk: 2.3,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
    tail: true,
    dorsalSpines: true,
    hunch: 0.25,
  },
  // Astra Militarum: olive fatigues and brimmed helmets on bare-faced humans, lasguns with tan stocks. Rank shows in
  // the head and kit (cap and sword for the officer, a banner for the standard bearer), never in bulk.
  'am-guardsman': {
    headShape: 'guard-helmet',
    rightWeapon: 'lasgun',
    leftWeapon: 'none',
    bulk: 1,
    hasBackpack: true,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'marine',
  },
  'am-sergeant': {
    headShape: 'guard-helmet',
    rightWeapon: 'lasgun',
    leftWeapon: 'power-sword',
    bulk: 1.05,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'marine',
  },
  'am-officer': {
    headShape: 'officer-cap',
    rightWeapon: 'plasma-pistol',
    leftWeapon: 'power-sword',
    bulk: 1.1,
    hasBackpack: false,
    shoulderPads: 'small',
    hasCape: true,
    skin: 'marine',
  },
  'am-veteran': {
    headShape: 'guard-helmet',
    rightWeapon: 'lasgun',
    leftWeapon: 'none',
    bulk: 1.08,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'marine',
  },
  'am-medic': {
    headShape: 'guard-helmet',
    rightWeapon: 'none',
    leftWeapon: 'none',
    bulk: 1.08,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'marine',
    chestCross: true,
  },
  'am-standard': {
    headShape: 'guard-helmet',
    rightWeapon: 'banner',
    leftWeapon: 'none',
    bulk: 1.08,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'marine',
  },
  // Armoured Sentinel: a two-legged walker, so it reuses the biped rig at a heavy bulk with a boxy cab for a head.
  'am-sentinel': {
    headShape: 'sentinel-cab',
    rightWeapon: 'plasma-cannon',
    leftWeapon: 'twin-claw',
    bulk: 1.9,
    hasBackpack: true,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
    limbColor: 'metal',
  },
  // Grey Knights: silver plate (paintScheme.primary) on torso and limbs, blue (secondary) as cloak and glow, gold trim.
  'gk-knight': {
    headShape: 'marine-helmet',
    rightWeapon: 'storm-bolter',
    leftWeapon: 'power-sword',
    bulk: 1.1,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
    limbColor: 'primary',
  },
  'gk-terminator': {
    headShape: 'terminator-helmet',
    rightWeapon: 'storm-bolter',
    leftWeapon: 'power-sword',
    bulk: 1.55,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
    limbColor: 'primary',
  },
  'gk-librarian': {
    headShape: 'terminator-helmet',
    rightWeapon: 'power-sword',
    leftWeapon: 'none',
    bulk: 1.55,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: true,
    skin: 'none',
    limbColor: 'primary',
    chestCore: true,
    halo: true,
  },
  // Nemesis Dreadknight: a walking suit, so the biped rig at monster bulk with a greatsword and a psycannon.
  'gk-dreadknight': {
    headShape: 'terminator-helmet',
    rightWeapon: 'warscythe',
    leftWeapon: 'plasma-cannon',
    bulk: 2.3,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
    limbColor: 'primary',
    chestCore: true,
  },
  // T'au Empire: cream armour (primary) with blue (secondary) cloth and glow, orange (trim) markings, slim pulse rifles.
  'tau-fire-warrior': {
    headShape: 'tau-helmet',
    rightWeapon: 'pulse-rifle',
    leftWeapon: 'none',
    bulk: 1,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'none',
    limbColor: 'primary',
  },
  'tau-shasui': {
    headShape: 'tau-helmet',
    rightWeapon: 'pulse-rifle',
    leftWeapon: 'none',
    bulk: 1.05,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
    limbColor: 'primary',
  },
  'tau-fireblade': {
    headShape: 'tau-helmet',
    rightWeapon: 'pulse-rifle',
    leftWeapon: 'none',
    bulk: 1.05,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: true,
    skin: 'none',
    limbColor: 'primary',
    capeColor: 'trim',
  },
  // Aun'Shar: an Ethereal in long robes (cape) with a glowing halo and an honour stave.
  'tau-ethereal': {
    headShape: 'tau-ethereal',
    rightWeapon: 'honour-stave',
    leftWeapon: 'none',
    bulk: 1,
    hasBackpack: true,
    shoulderPads: 'none',
    hasCape: true,
    skin: 'none',
    limbColor: 'primary',
    capeColor: 'trim',
    halo: true,
  },
  // Stealth battlesuits: tall slim suits with a fusion blaster; the Shas'ui share the look.
  'tau-stealth': {
    headShape: 'tau-helmet',
    rightWeapon: 'fusion-blaster',
    leftWeapon: 'burst-cannon',
    bulk: 1.5,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
    limbColor: 'primary',
    chestCore: true,
  },
  // Ghostkeel: a walking suit, so the biped rig at monster bulk with twin guns.
  'tau-ghostkeel': {
    headShape: 'tau-helmet',
    rightWeapon: 'fusion-blaster',
    leftWeapon: 'burst-cannon',
    bulk: 2.2,
    hasBackpack: true,
    shoulderPads: 'large',
    hasCape: false,
    skin: 'none',
    limbColor: 'primary',
    chestCore: true,
  },
  'generic-infantry': {
    headShape: 'generic-head',
    rightWeapon: 'bolt-rifle',
    leftWeapon: 'none',
    bulk: 1,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
  },
  'generic-heavy': {
    headShape: 'generic-head',
    rightWeapon: 'storm-bolter',
    leftWeapon: 'none',
    bulk: 1.5,
    hasBackpack: true,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'none',
  },
  'generic-monster': {
    headShape: 'generic-head',
    rightWeapon: 'twin-claw',
    leftWeapon: 'twin-claw',
    bulk: 2.2,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'none',
  },
  // Adepta Sororitas: near-black plate (primary) with bone tabards, crimson trim, brass metal and white hair.
  // Arms take the dark primary so the bone cloth reads as cloth, not as armour.
  'ade-canoness': {
    headShape: 'sister-bob',
    bulk: 1.15,
    shoulderPads: 'large',
    hasCape: true,
    skin: 'pale',
    limbColor: 'primary',
    tabard: true,
    rightWeapon: 'bolt-rifle',
    leftWeapon: 'power-sword',
    hasBackpack: false,
    halo: true,
    capeColor: 'trim',
  },
  'ade-sister': {
    headShape: 'sister-bob',
    bulk: 1.05,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'pale',
    limbColor: 'primary',
    tabard: true,
    rightWeapon: 'bolt-rifle',
    leftWeapon: 'none',
    hasBackpack: false,
  },
  'ade-sister-superior': {
    headShape: 'sister-bob',
    bulk: 1.05,
    shoulderPads: 'small',
    hasCape: true,
    skin: 'pale',
    limbColor: 'primary',
    tabard: true,
    rightWeapon: 'bolt-rifle',
    leftWeapon: 'power-sword',
    hasBackpack: false,
    capeColor: 'trim',
  },
  'ade-sister-flamer': {
    headShape: 'sister-bob',
    bulk: 1.05,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'pale',
    limbColor: 'primary',
    tabard: true,
    rightWeapon: 'flamer',
    leftWeapon: 'none',
    hasBackpack: true,
  },
  'ade-sister-heavy-flamer': {
    headShape: 'sister-bob',
    bulk: 1.15,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'pale',
    limbColor: 'primary',
    tabard: true,
    rightWeapon: 'heavy-flamer',
    leftWeapon: 'none',
    hasBackpack: true,
  },
  'ade-sister-simulacrum': {
    headShape: 'sister-bob',
    bulk: 1.05,
    shoulderPads: 'small',
    hasCape: false,
    skin: 'pale',
    limbColor: 'primary',
    tabard: true,
    rightWeapon: 'bolt-rifle',
    leftWeapon: 'banner',
    hasBackpack: false,
  },
  'ade-sacresant': {
    headShape: 'sister-hood',
    rightWeapon: 'mace',
    leftWeapon: 'tower-shield',
    bulk: 1.3,
    hasBackpack: false,
    shoulderPads: 'large',
    hasCape: true,
    skin: 'none',
    limbColor: 'primary',
    capeColor: 'trim',
    tabard: true,
  },
  // Arco-flagellants: bare pale skin, a crimson loincloth (trim leg colour), hooded brass mask, both arms flails.
  'ade-arco': {
    headShape: 'arco-mask',
    rightWeapon: 'flails',
    leftWeapon: 'flails',
    bulk: 0.95,
    hasBackpack: false,
    shoulderPads: 'none',
    hasCape: false,
    skin: 'pale',
    limbColor: 'skin',
    bareTorso: true,
    legColor: 'trim',
  },
}

export const ARTILLERY_CONFIG: Partial<Record<KitId, ArtilleryConfig>> = {
  'am-field-gun': { barrel: 'field-gun' },
  'am-rocket-battery': { barrel: 'rocket-rack' },
}

export const VEHICLE_CONFIG: Partial<Record<KitId, VehicleConfig>> = {
  'ork-deffkopta': { weapon: 'kustom-mega-blasta', hasRotor: true },
  'generic-vehicle': { weapon: 'none', hasRotor: false },
}
