// Canonical catalogue of the audio assets generated by tools/gen-audio.ts into public/audio/**
// (see tools/audio-manifest.json for the generation prompts/lines). Kept as a plain TS union rather
// than importing that JSON so the client bundle gets typo-safe autocomplete and has no runtime
// dependency on a build-tool file. If the manifest ever gains/removes an id, mirror the change here.

export type SfxId =
  | 'bolter-burst'
  | 'shoota-spray'
  | 'heavy-gun'
  | 'flamer'
  | 'psychic-zap'
  | 'hit-impact'
  | 'armour-save-clank'
  | 'invuln-shimmer'
  | 'melee-chainsword'
  | 'power-klaw-crunch'
  | 'ork-war-cry'
  | 'marine-shout'
  | 'model-death'
  | 'vehicle-explosion'
  | 'charge-rumble'
  | 'dice-rattle'
  | 'dice-land'
  | 'objective-captured-chime'
  | 'vp-scored-sting'
  | 'cp-gained-click'
  | 'stratagem-whoosh'
  | 'battle-shock-sting'
  | 'turn-start-horn'
  | 'ui-click'
  | 'ui-error'
  | 'victory-fanfare'
  | 'defeat-sting'

export type VoiceId =
  | 'narr-battle-round-one'
  | 'narr-movement-phase'
  | 'narr-shooting-phase'
  | 'narr-charge'
  | 'narr-fight-phase'
  | 'narr-command-phase'
  | 'narr-objective-taken'
  | 'narr-unit-destroyed'
  | 'narr-stratagem'
  | 'narr-victory'
  | 'narr-defeat'
  | 'narr-your-turn'

export type MusicId = 'ambient-battlefield-loop'

export type SoundId = SfxId | VoiceId | MusicId

export type SoundChannel = 'sfx' | 'voice' | 'music'

export const MUSIC_IDS: readonly MusicId[] = ['ambient-battlefield-loop']
export const LOOPING_SOUNDS: ReadonlySet<SoundId> = new Set<SoundId>(MUSIC_IDS)

export function channelFor(id: SoundId): SoundChannel {
  if ((MUSIC_IDS as readonly string[]).includes(id)) return 'music'
  if (id.startsWith('narr-')) return 'voice'
  return 'sfx'
}

export const VOICE_IDS: readonly VoiceId[] = [
  'narr-battle-round-one',
  'narr-movement-phase',
  'narr-shooting-phase',
  'narr-charge',
  'narr-fight-phase',
  'narr-command-phase',
  'narr-objective-taken',
  'narr-unit-destroyed',
  'narr-stratagem',
  'narr-victory',
  'narr-defeat',
  'narr-your-turn',
]

export const SFX_IDS: readonly SfxId[] = [
  'bolter-burst',
  'shoota-spray',
  'heavy-gun',
  'flamer',
  'psychic-zap',
  'hit-impact',
  'armour-save-clank',
  'invuln-shimmer',
  'melee-chainsword',
  'power-klaw-crunch',
  'ork-war-cry',
  'marine-shout',
  'model-death',
  'vehicle-explosion',
  'charge-rumble',
  'dice-rattle',
  'dice-land',
  'objective-captured-chime',
  'vp-scored-sting',
  'cp-gained-click',
  'stratagem-whoosh',
  'battle-shock-sting',
  'turn-start-horn',
  'ui-click',
  'ui-error',
  'victory-fanfare',
  'defeat-sting',
]

export const ALL_SOUND_IDS: readonly SoundId[] = [...SFX_IDS, ...VOICE_IDS, ...MUSIC_IDS]

/** public/audio/<id>.mp3, respecting Vite's base path (e.g. '/mallet-42k/' in production). */
export function audioUrl(id: SoundId): string {
  return `${import.meta.env.BASE_URL}audio/${id}.mp3`
}
