export { placementInfo, clickableUnitIds, unitClickAction, isPlacementDecision } from './decisions'
export type { PlacementInfo, PlacementActionType } from './decisions'
export { computeBoardClickDraft } from './boardClick'
export { useBoardClick } from './useBoardClick'
export { modelsAnchor, translatedPlacements, deploymentFormation, distance2D, combinedUnitModels, placementsOverlapExisting } from './geometry'
export type { Anchor2D } from './geometry'
export { PlacementOverlay } from './PlacementOverlay'
export { UnitsLayer } from './UnitsLayer'
export { UnitLabels } from './UnitLabels'
export { DeathGhosts } from './DeathGhosts'
export { modelNear, resolveMeasureLine } from './measure'
export type { MeasureLine } from './measure'
export { losStatusByUnit } from './lineOfSight'
