export { placementInfo, clickableUnitIds, unitClickAction, isPlacementDecision } from './decisions'
export type { PlacementInfo, PlacementActionType } from './decisions'
export { computeBoardClickDraft } from './boardClick'
export { useBoardClick } from './useBoardClick'
export { modelsAnchor, translatedPlacements, deploymentFormation, distance2D } from './geometry'
export type { Anchor2D } from './geometry'
export { PlacementOverlay } from './PlacementOverlay'
export { UnitsLayer } from './UnitsLayer'
export { DeathGhosts } from './DeathGhosts'
